### ISSUE TITLE
No display screen on running wallet/ W10

### ISSUE THREAD

**Issue by Jenova7** [Electra-project/electra-desktop#108]
@lappy#2421 from discord:
"Actually nothing is showing. When I click on the taskbar to put it in active mode, it just minimizes to tray. When I click on tray icon, taskbar status show but wallet app doesn't show. It's just the taskbar."
![lappy](https://user-images.githubusercontent.com/38404798/39049649-9da119fe-44a2-11e8-8382-83fa1658e762.png)

**Comment by ivangabriele** [comment]
If you right click on it, exit and restart the wallet, does it work ?

**Comment by Jenova7** [comment]
No, he did it many times, restart computer. nothing happened

**Comment by ivangabriele** [comment]
Thanks for the info here too. I will try to reproduce it.

**Comment by ivangabriele** [comment]
Fixed in v1.1.0:

- Linux (.deb): https://github.com/Electra-project/storage/releases/download/v0.0.0/electra-desktop_1.1.0_amd64.deb
- Linux (.rpm): https://github.com/Electra-project/storage/releases/download/v0.0.0/electra-desktop-1.1.0.x86_64.rpm
- MacOS: https://github.com/Electra-project/storage/releases/download/v0.0.0/electra-desktop-1.1.0.dmg
- Windows: https://github.com/Electra-project/storage/releases/download/v0.0.0/electra-desktop-setup-1.1.0.exe
